fixed bug

diff --git a/scripts/mkbeamer b/scripts/mkbeamer
--- a/scripts/mkbeamer
+++ b/scripts/mkbeamer
@@ -18,8 +18,8 @@ main() {
         >&2 echo "Please install pandoc to use this script."
         return 1
     fi
-    if ! command -v "$1" &>/dev/null; then
-        >&2 echo "Optional dependency $1 not found. Skipping."
+    if ! command -v notify-send &>/dev/null; then
+        >&2 echo "Optional dependency notify-send not found. Skipping."
         cmd_notify_send=:
     fi
 
diff --git a/scripts/mkrevealjs b/scripts/mkrevealjs
--- a/scripts/mkrevealjs
+++ b/scripts/mkrevealjs
@@ -21,7 +21,7 @@ pandoc_options="$pandoc_options --standalone"
 # src=...>) these needed files to some URL out there. This option makes pandoc
 # download them at 'compile-time' and embed them in the final file
 # --> pandoc(1) § Options affecting specific writers
-pandoc_options="$pandoc_options --embed-resources=true"
+#pandoc_options="$pandoc_options --embed-resources=true"
 
 # Include an automatically generated TOC in the output document. This option
 # has no effect unless -s/--standalone is used, and it has no effect on man,
@@ -47,8 +47,8 @@ main() {
         >&2 echo "Please install pandoc to use this script."
         return 1
     fi
-    if ! command -v "$1" &>/dev/null; then
-        >&2 echo "Optional dependency $1 not found. Skipping."
+    if ! command -v notify-send &>/dev/null; then
+        >&2 echo "Optional dependency notify-send not found. Skipping."
         cmd_notify_send=:
     fi
 
